package com.chess.client;


import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.HashMap;

import com.chess.client.chat.ChatPanel;
import com.chess.common.messages.Message;
import com.chess.common.messages.SendableMessage;
import com.chess.common.messages.StatusUpdate;
import com.chess.common.messages.StatusUpdate.StatusType;

import javafx.application.Platform;

public class Client {

	private final String address;
	private final int port;
	private Socket socket;
	private ObjectOutputStream out;
	private HashMap<Integer, String> onlineUsers = new HashMap<>();
	private ChatPanel view;
	
	/**
	 * Create a new client and his socket
	 * 
	 * @param address the address of the server
	 * @param port the port of the server
	 */
	public Client(String address, int port) {
		this.address = address;
		this.port = port;
		try {
			System.out.println("Creating sockets for " + address + ":" + port);
			this.socket = new Socket(address, port);
			this.out = new ObjectOutputStream(socket.getOutputStream());
		} catch (Exception e) {
			e.printStackTrace();
		}

		new Thread(new ClientReceive(this, socket)).start();
	}
	
	public void setView(ChatPanel view)
	{
		this.view = view;
	}
	
	/**
	 * Get server address
	 * 
	 * @return server address
	 */
	public String getAddress() {
		return address;
	}
	
	/**
	 * Get the port of the server
	 * 
	 * @return the port server
	 */
	public int getPort() {
		return port;
	}
	
	/**
	 * Get the stream which goes out
	 * (direction: the server)
	 * 
	 * @return the output stream to the server
	 */
	public ObjectOutputStream getOut() {
		return out;
	}
	
	/**
	 * Disconnect client to the server
	 */
	public void disconnectServer() {
		try {
			if(out != null)
				out.close();
			if(socket != null)
				socket.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	/**
	 * Get users ID (generated by the server) and their name
	 * 
	 * @return online users
	 */
	public HashMap<Integer, String> getOnlineUsers() {
		return onlineUsers;
	}
	
	public void sendMessage(Message mess)
	{
		try 
		{
		
		getOut().writeObject(mess);
		getOut().flush();
		
		} catch (Exception exc) {
			exc.printStackTrace();
		}
	}

	/**
	 * Manage the message which have been received
	 * 
	 * @param mess the message which have been received
	 */
	public void messageReceived(SendableMessage mess) {
		
		Message rawResult = new Message();
		
		if(mess instanceof StatusUpdate) 
		{
			StatusUpdate state = (StatusUpdate) mess;
			if(state.getType().equals(StatusType.LOGIN)) 
			{
				onlineUsers.put(state.getId(), state.getName());
			} 
			
			else 
			{
				onlineUsers.remove(state.getId());
			}
			rawResult.setName(state.getName());
			rawResult.setMessage(state.toShow());
		}
		
		if(mess instanceof Message)
		{
			rawResult = (Message)mess;
		}
		
		else 
		{
			onlineUsers.put(mess.getId(), mess.getName());
		}
		final Message result = new Message(rawResult);
		try {
			Platform.runLater(() -> view.getChatCTRL().printMessage(view.getReceivedText(),result));
		} catch (Exception e) {
			
		}
	}
}
